### PR TITLE
Allow sequences saved with qSlicerTrackedSequenceBrowserWriter to use…

### PR DESCRIPTION
**Pull request by Sunderlandkyl**
… content-specific storage nodes

### CODE REVIEW

**Comment by Sunderlandkyl** [comment]
@mholden8 this pull request allows nodes to be saved using their preferred storage methods. Ex. vtkMRMLStreamingVolume nodes can be saved as MKV files.

@lassoan The other possible solution to this that I can see is changing vtkMRMLSequenceNode::CreateDefaultStorageNode() to consult the NodeSequencer to find the correct sequence storage node based on the sequence contents.

**Comment by mholden8** [comment]
@Sunderlandkyl and I discussed why transform sequences were already saved in the preferred ".mha" file before now, and volume sequences were not already saved in their preferred file format. It is unclear to us at the moment. Investigating...

**Comment by Sunderlandkyl** [comment]
It's likely because of this:
https://github.com/SlicerRt/Sequences/blob/b9f29d13d7aa40287e86f01d552b7c1bfbe6de34/Sequences/MRML/vtkMRMLSequenceNode.cxx#L640-L669

Default storage node names are returned for volume and linear transform types.
We could modify this function to look through the registered NodeSequencers to find the proper storage node.

**Comment by lassoan** [comment]
> We could modify this function to look through the registered NodeSequencers to find the proper storage node.

This sounds like a good solution.

**Comment by Sunderlandkyl** [comment]
OK. This pull request will be obsolete then.

**Pull request closed without merging**
